version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: blood-donor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blood_donor_db
      MYSQL_USER: donor_user
      MYSQL_PASSWORD: donor_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: